services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"] # Path to collector config
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml # Mount collector config
    ports:
      - "${OTEL_GRPC_PORT}:4317" # OTLP gRPC port
      - "${OTEL_HTTP_PORT}:4318" # OTLP HTTP port
      - "8888:8888" # Collector metrics endpoint
      - "8889:8889" # zpages debug endpoint
    restart: unless-stopped
    # Auto-restart on failure, not on manual stop
    networks:
      - messenger-network
    env_file: .env

      # Connect to the shared microservices network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8888/metrics"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    depends_on:
      jaeger:
        condition: service_healthy

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: jaeger
    ports:
      - "${JAEGER_UI_PORT}:16686" # Jaeger UI port
    env_file: .env
    environment:
      - COLLECTOR_OTLP_ENABLED=true # Enable OpenTelemetry protocol
      - COLLECTOR_OTLP_HTTP_ENABLED=true # Accept OTLP over HTTP (4318)
      - COLLECTOR_OTLP_GRPC_ENABLED=true # Accept OTLP over gRPC (4317)
      - STORAGE_TYPE=badger # Embedded key-value storage
      - BADGER_EPHEMERAL=false # Persist data across restarts
      - BADGER_DIRECTORY_VALUE=/badger/data # Values (spans, tags, logs)
      - BADGER_DIRECTORY_KEY=/badger/key # Indexes for fast search
      - BADGER_MAINTENANCE_INTERVAL=5m # Compaction/cleanup interval
      - BADGER_TTL=168h # Data retention: 7 days
      - QUERY_BASE_PATH=/jaeger # Base path when behind reverse proxy
    volumes:
      - jaeger_data:/badger/data # Trace data volume
      - jaeger_key:/badger/key # Index data volume
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:${JAEGER_UI_PORT}"] # UI availability check
      interval: 5s # Check interval
      timeout: 3s # Check timeout
      retries: 3 # Retry attempts
      start_period: 5s # Delay before starting checks
    restart: unless-stopped
    networks:
      - messenger-network

networks:
  messenger-network:
    external: true

volumes: 
  jaeger_data: 
  jaeger_key: # Named volume for Jaeger indexes
